name: Multi-Platform Docker Build and Push

on:
  push:
    branches:
      - main

env:
  REGISTRY_IMAGE: penthertz/rfswiftdev

jobs:
  corebuild:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build corebuild image with two tags
        run: |
          docker buildx build --platform ${{ matrix.platform }} \
            -t corebuild:latest \
            -t ${{ env.REGISTRY_IMAGE }}:corebuild \
            -f Dockerfiles/SDR/corebuild.docker \
            --load \
            .

      - name: Push corebuild image to registry
        run: |
          docker push ${{ env.REGISTRY_IMAGE }}:corebuild

  sdr_light:
    runs-on: ubuntu-latest
    needs: corebuild  # Ensure corebuild job completes first
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build sdr_light image with two tags
        run: |
          docker buildx build --platform ${{ matrix.platform }} \
            -t sdr_light:latest \
            -t ${{ env.REGISTRY_IMAGE }}:sdr_light \
            -f Dockerfiles/SDR/sdr_light.docker \
            --load \
            .

      - name: Push sdr_light image to registry
        run: |
          docker push ${{ env.REGISTRY_IMAGE }}:sdr_light

  sdr_full:
    runs-on: ubuntu-latest
    needs: sdr_light  # Ensure sdr_light job completes first
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build sdr_full image with two tags
        run: |
          docker buildx build --platform ${{ matrix.platform }} \
            -t sdr_full:latest \
            -t ${{ env.REGISTRY_IMAGE }}:sdr_full \
            -f Dockerfiles/SDR/sdr_full.docker \
            --load \
            .

      - name: Push sdr_full image to registry
        run: |
          docker push ${{ env.REGISTRY_IMAGE }}:sdr_full