name: Multi-Platform Docker Build with Caching

env:
  REGISTRY_IMAGE: penthertz/rfswiftdev
  BUILD_PLATFORMS: linux/amd64,linux/arm64
  CACHE_PLATFORMS: linux_amd64-linux_arm64
  CACHE_REPO: penthertz/rfswiftdev
  DO_SPACES_ENDPOINT: ${{ secrets.BUCKET_URL }}
  DO_SPACES_REGION: ${{ secrets.BUCKET_REGION }}

on:
  push:
    branches:
      - main

jobs:
  corebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          version: latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push corebuild image with caching
        run: |
          docker buildx build --platform ${{ env.BUILD_PLATFORMS }} \
            --cache-from=type=registry,ref=${{ env.CACHE_REPO }}:cache_corebuild \
            --cache-to=type=registry,ref=${{ env.CACHE_REPO }}:cache_corebuild,mode=max \
            --push \
            -t ${{ env.REGISTRY_IMAGE }}:corebuild \
            -f Dockerfiles/SDR/corebuild.docker \
            .

  rfid:
    runs-on: ubuntu-latest
    needs: corebuild
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push rfid image with caching
        run: |
          docker buildx build --platform ${{ env.BUILD_PLATFORMS }} \
            --cache-from=type=registry,ref=${{ env.CACHE_REPO }}:cache_rfid \
            --cache-to=type=registry,ref=${{ env.CACHE_REPO }}:cache_rfid,mode=max \
            --build-arg BASE_IMAGE=${{ env.REGISTRY_IMAGE }}:corebuild \
            --push \
            -t ${{ env.REGISTRY_IMAGE }}:rfid \
            -f Dockerfiles/rfid.docker \
            .

  automotive:
    runs-on: ubuntu-latest
    needs: corebuild
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push automotive image with caching
        run: |
          docker buildx build --platform ${{ env.BUILD_PLATFORMS }} \
            --cache-from=type=registry,ref=${{ env.CACHE_REPO }}:cache_automotive \
            --cache-to=type=registry,ref=${{ env.CACHE_REPO }}:cache_automotive,mode=max \
            --build-arg BASE_IMAGE=${{ env.REGISTRY_IMAGE }}:corebuild \
            --push \
            -t ${{ env.REGISTRY_IMAGE }}:automotive \
            -f Dockerfiles/automotive.docker \
            .