name: SDR full - Multi-Platform Docker Build with Caching

env:
  REGISTRY_IMAGE: penthertz/rfswiftdevgh
  CACHE_REPO: penthertz/rfswiftdevgh
  DO_SPACES_ENDPOINT: ${{ secrets.BUCKET_URL }}
  DO_SPACES_REGION: ${{ secrets.BUCKET_REGION }}

on:
  push:
    branches:
      - main

jobs:
  corebuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/riscv64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          version: latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push corebuild image with caching
        run: |
          cd Dockerfiles
          TAG_PLATFORM=$(echo "${{ matrix.platform }}/corebuild" | tr '/' '_' | tr '-' '_')
          docker buildx build --platform ${{ matrix.platform }} \
            --build-arg ARCH=${{ matrix.platform }} \
            --cache-from type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM} \
            --cache-to type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM},mode=max \
            --push -t ${{ env.REGISTRY_IMAGE }}:${TAG_PLATFORM} .

  sdr_light:
    runs-on: ubuntu-latest
    needs: corebuild
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/riscv64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push sdr_light image with caching
        run: |
          cd Dockerfiles
          TAG_PLATFORM=$(echo "${{ matrix.platform }}/sdrlight" | tr '/' '_' | tr '-' '_')
          docker buildx build --platform ${{ matrix.platform }} \
            --build-arg ARCH=${{ matrix.platform }} \
            --cache-from type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM} \
            --cache-to type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM},mode=max \
            --push -t ${{ env.REGISTRY_IMAGE }}:${TAG_PLATFORM} .

  extraoot:
    runs-on: ubuntu-latest
    needs: sdr_light
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/riscv64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push sdr_full image with caching
        run: |
          cd Dockerfiles
          TAG_PLATFORM=$(echo "${{ matrix.platform }}/sdrfull" | tr '/' '_' | tr '-' '_')
          docker buildx build --platform ${{ matrix.platform }} \
            --build-arg ARCH=${{ matrix.platform }} \
            --cache-from type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM} \
            --cache-to type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM},mode=max \
            --push -t ${{ env.REGISTRY_IMAGE }}:${TAG_PLATFORM} .

  extrasoft:
    runs-on: ubuntu-latest
    needs: sdr_light
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/riscv64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push sdr_full image with caching
        run: |
          cd Dockerfiles
          TAG_PLATFORM=$(echo "${{ matrix.platform }}/sdrfull" | tr '/' '_' | tr '-' '_')
          docker buildx build --platform ${{ matrix.platform }} \
            --build-arg ARCH=${{ matrix.platform }} \
            --cache-from type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM} \
            --cache-to type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM},mode=max \
            --push -t ${{ env.REGISTRY_IMAGE }}:${TAG_PLATFORM} .

  mldlsofts:
    runs-on: ubuntu-latest
    needs: sdr_light
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/riscv64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push sdr_full image with caching
        run: |
          cd Dockerfiles
          TAG_PLATFORM=$(echo "${{ matrix.platform }}/sdrfull" | tr '/' '_' | tr '-' '_')
          docker buildx build --platform ${{ matrix.platform }} \
            --build-arg ARCH=${{ matrix.platform }} \
            --cache-from type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM} \
            --cache-to type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM},mode=max \
            --push -t ${{ env.REGISTRY_IMAGE }}:${TAG_PLATFORM} .

  sdr_light_antsdr:
    runs-on: ubuntu-latest
    needs: corebuild
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/riscv64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push sdr_light_antsdr image with caching
        run: |
          cd Dockerfiles
          TAG_PLATFORM=$(echo "${{ matrix.platform }}/sdrlightantsdr" | tr '/' '_' | tr '-' '_')
          docker buildx build --platform ${{ matrix.platform }} \
            --build-arg ARCH=${{ matrix.platform }} \
            --cache-from type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM} \
            --cache-to type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM},mode=max \
            --push -t ${{ env.REGISTRY_IMAGE }}:${TAG_PLATFORM} .

  sdr_light_rtlsdrv4:
    runs-on: ubuntu-latest
    needs: corebuild
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/riscv64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push sdr_light_rtlsdrv4 image with caching
        run: |
          cd Dockerfiles
          TAG_PLATFORM=$(echo "${{ matrix.platform }}/sdrlightrtlsdrv4" | tr '/' '_' | tr '-' '_')
          docker buildx build --platform ${{ matrix.platform }} \
            --build-arg ARCH=${{ matrix.platform }} \
            --cache-from type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM} \
            --cache-to type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM},mode=max \
            --push -t ${{ env.REGISTRY_IMAGE }}:${TAG_PLATFORM} .

  telecom:
    runs-on: ubuntu-latest
    needs: sdr_light
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/riscv64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push telecom image with caching
        run: |
          cd Dockerfiles
          TAG_PLATFORM=$(echo "${{ matrix.platform }}/telecom" | tr '/' '_' | tr '-' '_')
          docker buildx build --platform ${{ matrix.platform }} \
            --build-arg ARCH=${{ matrix.platform }} \
            --cache-from type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM} \
            --cache-to type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM},mode=max \
            --push -t ${{ env.REGISTRY_IMAGE }}:${TAG_PLATFORM} .

  wifi:
    runs-on: ubuntu-latest
    needs: sdr_light
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/riscv64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push wifi image with caching
        run: |
          cd Dockerfiles
          TAG_PLATFORM=$(echo "${{ matrix.platform }}/wifi" | tr '/' '_' | tr '-' '_')
          docker buildx build --platform ${{ matrix.platform }} \
            --build-arg ARCH=${{ matrix.platform }} \
            --cache-from type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM} \
            --cache-to type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM},mode=max \
            --push -t ${{ env.REGISTRY_IMAGE }}:${TAG_PLATFORM} .

  bluetooth:
    runs-on: ubuntu-latest
    needs: sdr_light
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/riscv64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push bluetooth image with caching
        run: |
          cd Dockerfiles
          TAG_PLATFORM=$(echo "${{ matrix.platform }}/bluetooth" | tr '/' '_' | tr '-' '_')
          docker buildx build --platform ${{ matrix.platform }} \
            --build-arg ARCH=${{ matrix.platform }} \
            --cache-from type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM} \
            --cache-to type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM},mode=max \
            --push -t ${{ env.REGISTRY_IMAGE }}:${TAG_PLATFORM} .

  rfid:
    runs-on: ubuntu-latest
    needs: corebuild
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/riscv64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push rfid image with caching
        run: |
          cd Dockerfiles
          TAG_PLATFORM=$(echo "${{ matrix.platform }}/rfid" | tr '/' '_' | tr '-' '_')
          docker buildx build --platform ${{ matrix.platform }} \
            --build-arg ARCH=${{ matrix.platform }} \
            --cache-from type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM} \
            --cache-to type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM},mode=max \
            --push -t ${{ env.REGISTRY_IMAGE }}:${TAG_PLATFORM} .

  automotive:
    runs-on: ubuntu-latest
    needs: corebuild
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/riscv64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push automotive image with caching
        run: |
          cd Dockerfiles
          TAG_PLATFORM=$(echo "${{ matrix.platform }}/automotive" | tr '/' '_' | tr '-' '_')
          docker buildx build --platform ${{ matrix.platform }} \
            --build-arg ARCH=${{ matrix.platform }} \
            --cache-from type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM} \
            --cache-to type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM},mode=max \
            --push -t ${{ env.REGISTRY_IMAGE }}:${TAG_PLATFORM} .

  reversing:
    runs-on: ubuntu-latest
    needs: corebuild
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/riscv64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push reversing image with caching
        run: |
          cd Dockerfiles
          TAG_PLATFORM=$(echo "${{ matrix.platform }}/reversing" | tr '/' '_' | tr '-' '_')
          docker buildx build --platform ${{ matrix.platform }} \
            --build-arg ARCH=${{ matrix.platform }} \
            --cache-from type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM} \
            --cache-to type=registry,ref=${{ env.CACHE_REPO }}:${TAG_PLATFORM},mode=max \
            --push -t ${{ env.REGISTRY_IMAGE }}:${TAG_PLATFORM} .